name: flutterclient
description: A generic Flutter app for JVx applications.
homepage: https://www.sibvisions.com
repository: https://github.com/sibvisions/flutterclient.git
issue_tracker: https://github.com/sibvisions/flutterclient/issues

publish_to: "none"

version: 1.0.1+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  http: ^0.13.0
  dartz: ^0.10.0-nullsafety.1
  get_it: ^6.0.0
  shared_preferences: ^2.0.4
  encrypt: ^5.0.0-beta.1
  uuid: ^3.0.1
  device_info: ^2.0.0
  package_info: ^2.0.0
  archive: ^3.1.2
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.1
  intl: ^0.17.0
  auto_size_text: ^3.0.0-nullsafety.0
  font_awesome_flutter: ^9.0.0-nullsafety
  flutter_picker: ^2.0.0
  collection: ^1.15.0
  sticky_headers: ^0.2.0
  flutter_html: ^2.0.0-nullsafety.0
  yaml: ^3.1.0
  sqflite: ^2.0.0+3
  logging: ^1.0.0
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  flutter_slidable: ^0.6.0-nullsafety.0
  path: ^1.8.0
  file_picker: ^3.0.0
  image_picker: ^0.7.3
  universal_html: ^2.0.7
  charts_flutter: ^0.10.0
  flutter_gauge: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/config/
    - assets/env/
    - assets/images/
    - assets/version/
